### ISSUE TITLE
Is there any chance rearranging marks function will be added?

### ISSUE THREAD

**Issue by arilebedey** [mike-jl/harpoonEx#4]
I'm using harpoon2 (haven't tried first version) and am looking for a way to reorder the marks.

I have seen only one successful mention of this functionality actually working in harpoon in the harpoon repo, so I might look there, but I don't think it will work in harpoon2 since the only person mentioning rearranging marks was talking about it as something that should be implemented.

**Comment by LehMichael** [comment]
Like with a keybind? Right now it only works in the menu (normal or telescope) afaik, but i can look into that if this is what you mean.

**Comment by arilebedey** [comment]
Thanks you for your response! Are you saying there already is a hotkey to move marks up and down from the plugin menu ? Do you mean that its already built-in into the main harpoon or your extension? Can't find a mention of this in either... (I'm using harpoon2 branch)

**Comment by LehMichael** [comment]
The regular plugin menu behaves like a buffer, you can move a mark by cutting it with dd and pasting it somewhere else with p. In the harpoon menu the keys are documented in the readme.
